version: '3.8'

services:
  lumina-frontend:
    build: .
    container_name: lumina_frontend
    ports:
      - "8081:80"
    depends_on:
      - lumina-api
    restart: always

  lumina-api:
    image: node:20-alpine
    container_name: lumina_api
    working_dir: /app
    volumes:
      - ./server.js:/app/server.js:ro
      - ./package.json:/app/package.json:ro
      - ./node_modules:/app/node_modules:ro
      - /home/abimael/projetos/AutomatedPythonVideoMaker/cache:/data
    expose:
      - "3001"
    command: sh -c "mkdir -p /data && node --watch server.js"
    restart: always